### ISSUE TITLE
join with ensime?

### ISSUE THREAD

**Issue by fommil** [ensime/emacs-scala-mode#100]
Just a thought, but we'd be happy to help with PR reviews and general maintenance over at the `ensime` organisation.

Would you consider moving the `scala-mode2` and `sbt-mode` packages to `ensime`? You retain full write access, of course.

**Comment by hvesalai** [comment]
That would be great so long as scala-mode2 and sbt-mode would still work stand-alone, i.e. without the ensime server running.

**Comment by fommil** [comment]
@hvesalai yup! I often use them without ENSIME. Practicalities are:

1. transfer to myself or another owner of ensime (in settings)
2. I'll add to `ensime`, and add you as an admin for the repos
3. you fork back to your account

then all the issues / PRs get moved over as well.

**Comment by fommil** [comment]
4. ping MELPA with the new URLs (I'll do that)

**Comment by hvesalai** [comment]
Can't transfer to you because you already have a repository called scala-mode2.

**Comment by fommil** [comment]
I'll rename, one sec (or merge my PR then I'll delete?)

**Comment by fommil** [comment]
renamed

**Comment by hvesalai** [comment]
No can do, renaming was not enough. You need to remove it completely (be off the network). Or then give me ensime admin rights for a second so I can transfer directly there.

**Comment by fommil** [comment]
I'll add you as owner temporarily

**Comment by hvesalai** [comment]
Done! Please inspect the damages

**Comment by fommil** [comment]
nice, I'll leave you as a member of the Emacs panel if that's alright

**Comment by fommil** [comment]
@hvesalai nice, ok and now you fork back again. I'll do the necessary on melpa.

**Comment by fommil** [comment]
thanks!
