### ISSUE TITLE
ensime is not a dependency of scala-mode

### ISSUE THREAD

**Issue by davidshen84** [ensime/emacs-scala-mode#117]
I tried to install `scala-mode` from MELPA. But I got:

```
Entering directory `/home/david/.emacs.d/elpa/scala-mode-20160813.304/'
ob-scala.el:27:1:Error: Cannot open load file: no such file or directory, ensime
```

I have manually install `ensime` package before installing `scala-mode`.

My Emacs version is **GNU Emacs 24.5.1 (x86_64-unknown-cygwin)**

**Comment by hvesalai** [comment]
@reactormonk, @fommil requiring ensime from ob-scala.el should be done so that it fails quietly if ensime it is not present.

`(require FEATURE &optional FILENAME NOERROR)`, i.e. `(require ensime "ensime" t)`

**Comment by reactormonk** [comment]
All functionality of this ob-scala depends on ensime. The logic that doesn't hasn't been merged yet.

**Comment by fommil** [comment]
I understand this is all going to be moved into org mode at some point anyway by @reactormonk and merged with the existing impl (turns out they already had one)

**Comment by fommil** [comment]
#114
