### ISSUE TITLE
scala-indent:align-forms

### ISSUE THREAD

**Issue by nloyola** [ensime/emacs-scala-mode#120]
I've set `scala-indent:align-forms` to `t` but the indentation is wrong. This is what I get:

``` scala
// (setq scala-indent:align-forms t)

val x = if (foo)
    true
        else
          false
```

The line that has `true` is not indented correctly.

I'm using scala mode version **20160902.525** on Emacs 25.1-rc2 running on Ubuntu 16.04.

**Comment by hvesalai** [comment]
indeed a bug

**Comment by fommil** [comment]
Scalariform isn't great with this either. If you find a scalariform setting that makes this look pretty, please let me know.

**Comment by hvesalai** [comment]
This has worked and I think it got broken at some point

**Comment by hvesalai** [comment]
the bug is that `scala-indent:goto-body-anchor` goes to `scala-indent:backward-sexp-to-beginning-of-line` instead of going to the beginning of `if`
