### ISSUE TITLE
fill-paragraph does not respect the prefix arg

### ISSUE THREAD

**Issue by jeberger** [ensime/emacs-scala-mode#125]
When given a prefix argument, fill-paragraph should justify the paragraph instead of simply wrapping it. Currently it ignores the prefix argument.

This can be fixed by replacing the two calls to `(fill-paragraph)` with `(apply #'fill-paragraph args)` inside `scala-paragraph:fill-paragraph`.

**Comment by fommil** [comment]
could you please send that as a PR?
