### ISSUE TITLE
Wrong indentation after import `scala.util.Try`

### ISSUE THREAD

**Issue by jilen** [ensime/emacs-scala-mode#132]
+ Emacs: 25.1.1
+ OS: Archlinux

![screenshot from 2017-03-23 11-54-19](https://cloud.githubusercontent.com/assets/546573/24231445/b38d72ee-0fbf-11e7-8d21-4318d909da13.png)

Seems `Try` was treat as `keyword`

**Comment by fommil** [comment]
Pull request with fix?

**Comment by hvesalai** [comment]
Can't reproduce. Also `try` as a keyword would be the same color as `import`. Now it is in different color meaning it is (at least by fontlock) detected as type.

It almost looks like you have case-insensitive regex and that is causing the problem.

**Comment by hvesalai** [comment]
https://www.gnu.org/software/emacs/manual/html_node/emacs/Search-Case.html

Have you touched `case-fold-search`? What is its value?

**Comment by jilen** [comment]
```
case-fold-search is a variable defined in ‘C source code’.
Its value is t

  Automatically becomes buffer-local when set.

Documentation:
Non-nil if searches and matches should ignore case.

You can customize this variable.

[back]

```

**Comment by hvesalai** [comment]
Hmm... I also have `t`

**Comment by jilen** [comment]
Force set it to nil solve my issue
```lisp
(defun setup-scala ()
    (setq case-fold-search nil))

(add-hook 'scala-mode-hook 'setup-scala)
```

**Comment by hvesalai** [comment]
Ok, but that doesn't explain the bug since I have it also se to `t` and don't have the bug
