### ISSUE TITLE
`**` at end of multiline comment cause issue

### ISSUE THREAD

**Issue by martin-liu** [ensime/emacs-scala-mode#140]
Hi, 

I found a bug that when there's 2 star(`**`) at the end of multiline comment, it will treat all code below it as comment. See detail below:

With `**`: 
![image](https://user-images.githubusercontent.com/1459760/26904166-7e186e72-4b95-11e7-8c39-6e7a98558bd7.png)

With `*`:
![image](https://user-images.githubusercontent.com/1459760/26904184-8deb15fc-4b95-11e7-916e-3fb1ce320396.png)

**Comment by hvesalai** [comment]
Cannot repro. Please see that you are using the latest version of the mode

![image](https://user-images.githubusercontent.com/861035/26904412-717c7280-4bea-11e7-8686-aeb14671da9a.png)

**Comment by martin-liu** [comment]
@hvesalai It's weird that you don't see the issue.

I checked the version is `scala-mode-20170531.44`.

Also I tried to add `**/` in https://github.com/ensime/emacs-scala-mode/blob/master/scala-mode-syntax.el#L611
![image](https://user-images.githubusercontent.com/1459760/26905886-bbd8d180-4b9e-11e7-943f-8d0970aeff1d.png)


Then it works for me, see
![image](https://user-images.githubusercontent.com/1459760/26905856-986bfc9a-4b9e-11e7-8083-ddd78fb32f58.png)



Since this function is not regexp match, it will have issue if I use more than 2 stars like `/***` or `***/`

![image](https://user-images.githubusercontent.com/1459760/26906044-95db05ce-4b9f-11e7-9dbb-fa0e9bab2257.png)

**Comment by fommil** [comment]
Maybe Emacs version?

**Comment by martin-liu** [comment]
@fommil my emacs version is: 
![image](https://user-images.githubusercontent.com/1459760/26916302-b2321822-4bde-11e7-8211-4e4f0d246b7c.png)

**Comment by hvesalai** [comment]
Ok. My bad, I'm not using the latest version. @VlachJosef can you see if your latest change broke this.

**Comment by VlachJosef** [comment]
yes, this is broken due to how `scala-syntax:propertize-special-symbols` is looking for special symbols.

Currently it is using:

```elisp
(member match '("/*" "//" "/**" "</" "*/"))
```
to eliminate some cases, but it needs to be little more clever to cover all other variants. So some regexp match will be needed at this point.

**Comment by martin-liu** [comment]
👍 👍 👍

**Comment by yyadavalli** [comment]
Fixed in #141
