### ISSUE TITLE
String interpolation support

### ISSUE THREAD

**Issue by hvesalai** [ensime/emacs-scala-mode#60]
The fontlock branch now has a first attempt at string interpolation. It still requires string-propertise functions to be rewritten to understand nested strings inside ${}.

```scala
"Foo ${ "This isn't supported now" } Zot"
```

(Seems that github comment formatter doesn't either support string interpolation)

**Comment by Pyppe** [comment]
:+1:

**Comment by fommil** [comment]
should we close this as "use ensime if you want this support"?
