### ISSUE TITLE
imenu support for scalatest-style strings

### ISSUE THREAD

**Issue by fommil** [ensime/emacs-scala-mode#91]
i.e. pick scalatest descriptions up as `(test)"do the thing with the thing"`

**Comment by IvanMalison** [comment]
I wouldn't mind doing this, but was under the impression that you ensime people feel pretty strongly that https://github.com/ensime/ensime-server/issues/471 is the right way to do things (I actually definitely agree).

**Comment by fommil** [comment]
Well it's always good to have a regex fallback :-)
