### ISSUE TITLE
Indention of lambdas

### ISSUE THREAD

**Issue by pishen** [ensime/emacs-scala-mode#94]
For the code:

``` scala
seq
  .map { x =>
    val t = x + 1
  }
```

When I hit enter at the end of `x + 1`, it become

``` scala
seq
  .map { x =>
  val t = x + 1

  }
```

which should be

``` scala
seq
  .map { x =>
    val t = x + 1

  }
```

**Comment by pishen** [comment]
Looks like it only happen when `.map` is on the second line. (updated)

**Comment by hvesalai** [comment]
So can you give updated example of what happens and what you expect

**Comment by pishen** [comment]
I already edited it on the original post https://github.com/hvesalai/scala-mode2/issues/94#issue-92813638

**Comment by hvesalai** [comment]
This is a bug in scala-mode2. You may work around it by placing the dot on the first line.

```scala
seq.
  map { x =>
    val t = x + 1
  }
```

**Comment by pishen** [comment]
Also when hitting enter at
```scala
seq.map {
  x =>
    val t = x + 1
}
```
It becomes
```scala
seq.map {
  x =>
  val t = x + 1

}
```
which sould be
```scala
seq.map {
  x =>
    val t = x + 1
    
}
```
I guess it is from the same problem?

**Comment by hvesalai** [comment]
Yes, there is currently on support for that either. It has been designed to work as 

```scala
seq.map { x =>
  val t = x + 1
}
```

The only support for such is with the `case` word, i.e.

```scala
seq.map {
  case x =>
    val t = x + 1
}
```

**Comment by 4lex1v** [comment]
I'm suffering from this problem too. Tried to trace the indenting logic, as far as i could understand there are two functions involved into computing the indentation in this case: `scala-indent:goto-run-on-anchor` and `scala-indent:goto-block-anchor`. Having the following code:

``` emacs-lisp
ws
  .flatMap { response =>

}
```

The initial point will be before `ws` rather then the dot before `flatMap`. Wonder if i should modify an existing rule or add a new one before those i've mentioned above? I'm ready to work on this issue and contribute

**Comment by hvesalai** [comment]
I think modifying the existing rule is the cleanest solution. I don't know why this bug came to be, but I think it has something to do with the fact that I thought the form is not valid scala. I think I had the impression that the dot must be at the end of the line.

**Comment by fommil** [comment]
Interesting, yeah this he's started to become pretty idiomatic Scala with all the streaming libraries. I prefer putting short closures on the same line as their inputs TBH.

**Comment by 4lex1v** [comment]
The problem is not with one-line lambdas, but with multiline case deconstructors, e.g:

```scala
ws
  .url("...")
  .map(_.getSomething)
  .flatMap {
    case Some(value) => Future.success(value)
    case None => Future.failed(...)
}
```

Unfortunately examples as above are painful to edit

**Comment by hvesalai** [comment]
Yes, this is how I format it and how I tested it when writing the indentation code

```scala
ws.
  url("...").
  map(_.getSomething).
  flatMap {
    case Some(value) => Future.success(value)
    case None => Future.failed(...)
  }
```

if we want @4lex1v 's version to work, then the `scala-indent:goto-run-on-anchor` needs to be changed so it stops at the `.` if it follows a valid `nl`. The rule for a valid `nl` is defined in https://www.scala-lang.org/files/archive/spec/2.11/01-lexical-syntax.html#newline-characters.

**Comment by hvesalai** [comment]
The offending line is this: https://github.com/ensime/emacs-scala-mode/blob/master/scala-mode-indent.el#L294

The question now is, could we say that that rule is not to be used in the `keywords-only-strategy` or that we the `keywords-only-strategy` we should return a `nil` before this row if the `char-after` is a `.`.

Regarding that, there are two alternatives: a mud ball patch, which is to create a new strategy used only by `goto-run-on-anchor` that would do exactly that, or then the clean solution of studying where the `keywords-only-strategy` is used and if all callers would agree on this new definition of `run-on-p`.

I don't like mud balls.

**Comment by hvesalai** [comment]
(comment redacted as utter bollocks)

**Comment by hvesalai** [comment]
Ok, so an other take: https://github.com/ensime/emacs-scala-mode/blob/master/scala-mode-indent.el#L600

Here we skip back sexps until we reach a beginning of line. Since `.` is ignored as punctuation when skipping sexps, it skips from the point before `flatMap` (but after `.`) to the beginning of `map` (but after `.`) and so forth until it reaches point before `ws` which is at the beginning of line.

**Comment by 4lex1v** [comment]
@hvesalai how hard would it be to support both indentation schemes? Would it require some sort of `defcustom` variable or changes to the algorithm would be enough?

**Comment by hvesalai** [comment]
This is also broken:

```
foo(foo
      ,bar)
```

**Comment by hvesalai** [comment]
@4lex1v if I fix it, will you test it?

**Comment by 4lex1v** [comment]
@hvesalai yes

**Comment by hvesalai** [comment]
And by testing we mean that it should be checked that it doesn't break anything outside what it means to fix. So please reindent large amounts of code with this.

**Comment by 4lex1v** [comment]
@hvesalai The fix for my case works, i'll test it more today, thank you. Though your examples `foo(foo, bar)` look like this:

``` scala
object test {
  foo(foo
    ,bar)
}
```

which is a bit different

**Comment by hvesalai** [comment]
Yes, that is a different rule (parameter alignment)
